server:
  port: 8080
  undertow:
    threads:
      io: 16
      worker: 256
    buffer-size: 1024
    direct-buffers: true
  servlet:
    context-path: /front
jackson:
  default-property-inclusion: non_null
spring:
  application:
    name: candy-crush-letter-front
  aop:
    auto: true
    proxy-target-class: false
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    check-template-location: true
logging:
  level:
    root: info
